require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GoodAnswersController do

  # This should return the minimal set of attributes required to create a valid
  # GoodAnswer. As you add validations to GoodAnswer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GoodAnswersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all good_answers as @good_answers" do
      good_answer = GoodAnswer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:good_answers).should eq([good_answer])
    end
  end

  describe "GET show" do
    it "assigns the requested good_answer as @good_answer" do
      good_answer = GoodAnswer.create! valid_attributes
      get :show, {:id => good_answer.to_param}, valid_session
      assigns(:good_answer).should eq(good_answer)
    end
  end

  describe "GET new" do
    it "assigns a new good_answer as @good_answer" do
      get :new, {}, valid_session
      assigns(:good_answer).should be_a_new(GoodAnswer)
    end
  end

  describe "GET edit" do
    it "assigns the requested good_answer as @good_answer" do
      good_answer = GoodAnswer.create! valid_attributes
      get :edit, {:id => good_answer.to_param}, valid_session
      assigns(:good_answer).should eq(good_answer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GoodAnswer" do
        expect {
          post :create, {:good_answer => valid_attributes}, valid_session
        }.to change(GoodAnswer, :count).by(1)
      end

      it "assigns a newly created good_answer as @good_answer" do
        post :create, {:good_answer => valid_attributes}, valid_session
        assigns(:good_answer).should be_a(GoodAnswer)
        assigns(:good_answer).should be_persisted
      end

      it "redirects to the created good_answer" do
        post :create, {:good_answer => valid_attributes}, valid_session
        response.should redirect_to(GoodAnswer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved good_answer as @good_answer" do
        # Trigger the behavior that occurs when invalid params are submitted
        GoodAnswer.any_instance.stub(:save).and_return(false)
        post :create, {:good_answer => {}}, valid_session
        assigns(:good_answer).should be_a_new(GoodAnswer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GoodAnswer.any_instance.stub(:save).and_return(false)
        post :create, {:good_answer => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested good_answer" do
        good_answer = GoodAnswer.create! valid_attributes
        # Assuming there are no other good_answers in the database, this
        # specifies that the GoodAnswer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GoodAnswer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => good_answer.to_param, :good_answer => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested good_answer as @good_answer" do
        good_answer = GoodAnswer.create! valid_attributes
        put :update, {:id => good_answer.to_param, :good_answer => valid_attributes}, valid_session
        assigns(:good_answer).should eq(good_answer)
      end

      it "redirects to the good_answer" do
        good_answer = GoodAnswer.create! valid_attributes
        put :update, {:id => good_answer.to_param, :good_answer => valid_attributes}, valid_session
        response.should redirect_to(good_answer)
      end
    end

    describe "with invalid params" do
      it "assigns the good_answer as @good_answer" do
        good_answer = GoodAnswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GoodAnswer.any_instance.stub(:save).and_return(false)
        put :update, {:id => good_answer.to_param, :good_answer => {}}, valid_session
        assigns(:good_answer).should eq(good_answer)
      end

      it "re-renders the 'edit' template" do
        good_answer = GoodAnswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GoodAnswer.any_instance.stub(:save).and_return(false)
        put :update, {:id => good_answer.to_param, :good_answer => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested good_answer" do
      good_answer = GoodAnswer.create! valid_attributes
      expect {
        delete :destroy, {:id => good_answer.to_param}, valid_session
      }.to change(GoodAnswer, :count).by(-1)
    end

    it "redirects to the good_answers list" do
      good_answer = GoodAnswer.create! valid_attributes
      delete :destroy, {:id => good_answer.to_param}, valid_session
      response.should redirect_to(good_answers_url)
    end
  end

end
