require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserFeedbackRepliesController do

  # This should return the minimal set of attributes required to create a valid
  # UserFeedbackReply. As you add validations to UserFeedbackReply, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "user_feedback_id" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UserFeedbackRepliesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all user_feedback_replies as @user_feedback_replies" do
      user_feedback_reply = UserFeedbackReply.create! valid_attributes
      get :index, {}, valid_session
      assigns(:user_feedback_replies).should eq([user_feedback_reply])
    end
  end

  describe "GET show" do
    it "assigns the requested user_feedback_reply as @user_feedback_reply" do
      user_feedback_reply = UserFeedbackReply.create! valid_attributes
      get :show, {:id => user_feedback_reply.to_param}, valid_session
      assigns(:user_feedback_reply).should eq(user_feedback_reply)
    end
  end

  describe "GET new" do
    it "assigns a new user_feedback_reply as @user_feedback_reply" do
      get :new, {}, valid_session
      assigns(:user_feedback_reply).should be_a_new(UserFeedbackReply)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_feedback_reply as @user_feedback_reply" do
      user_feedback_reply = UserFeedbackReply.create! valid_attributes
      get :edit, {:id => user_feedback_reply.to_param}, valid_session
      assigns(:user_feedback_reply).should eq(user_feedback_reply)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UserFeedbackReply" do
        expect {
          post :create, {:user_feedback_reply => valid_attributes}, valid_session
        }.to change(UserFeedbackReply, :count).by(1)
      end

      it "assigns a newly created user_feedback_reply as @user_feedback_reply" do
        post :create, {:user_feedback_reply => valid_attributes}, valid_session
        assigns(:user_feedback_reply).should be_a(UserFeedbackReply)
        assigns(:user_feedback_reply).should be_persisted
      end

      it "redirects to the created user_feedback_reply" do
        post :create, {:user_feedback_reply => valid_attributes}, valid_session
        response.should redirect_to(UserFeedbackReply.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_feedback_reply as @user_feedback_reply" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserFeedbackReply.any_instance.stub(:save).and_return(false)
        post :create, {:user_feedback_reply => { "user_feedback_id" => "invalid value" }}, valid_session
        assigns(:user_feedback_reply).should be_a_new(UserFeedbackReply)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserFeedbackReply.any_instance.stub(:save).and_return(false)
        post :create, {:user_feedback_reply => { "user_feedback_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_feedback_reply" do
        user_feedback_reply = UserFeedbackReply.create! valid_attributes
        # Assuming there are no other user_feedback_replies in the database, this
        # specifies that the UserFeedbackReply created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UserFeedbackReply.any_instance.should_receive(:update_attributes).with({ "user_feedback_id" => "" })
        put :update, {:id => user_feedback_reply.to_param, :user_feedback_reply => { "user_feedback_id" => "" }}, valid_session
      end

      it "assigns the requested user_feedback_reply as @user_feedback_reply" do
        user_feedback_reply = UserFeedbackReply.create! valid_attributes
        put :update, {:id => user_feedback_reply.to_param, :user_feedback_reply => valid_attributes}, valid_session
        assigns(:user_feedback_reply).should eq(user_feedback_reply)
      end

      it "redirects to the user_feedback_reply" do
        user_feedback_reply = UserFeedbackReply.create! valid_attributes
        put :update, {:id => user_feedback_reply.to_param, :user_feedback_reply => valid_attributes}, valid_session
        response.should redirect_to(user_feedback_reply)
      end
    end

    describe "with invalid params" do
      it "assigns the user_feedback_reply as @user_feedback_reply" do
        user_feedback_reply = UserFeedbackReply.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserFeedbackReply.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_feedback_reply.to_param, :user_feedback_reply => { "user_feedback_id" => "invalid value" }}, valid_session
        assigns(:user_feedback_reply).should eq(user_feedback_reply)
      end

      it "re-renders the 'edit' template" do
        user_feedback_reply = UserFeedbackReply.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserFeedbackReply.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_feedback_reply.to_param, :user_feedback_reply => { "user_feedback_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_feedback_reply" do
      user_feedback_reply = UserFeedbackReply.create! valid_attributes
      expect {
        delete :destroy, {:id => user_feedback_reply.to_param}, valid_session
      }.to change(UserFeedbackReply, :count).by(-1)
    end

    it "redirects to the user_feedback_replies list" do
      user_feedback_reply = UserFeedbackReply.create! valid_attributes
      delete :destroy, {:id => user_feedback_reply.to_param}, valid_session
      response.should redirect_to(user_feedback_replies_url)
    end
  end

end
